using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Net.Http;
using Infrastructure;

namespace Test
{
    [TestClass()]
    public class FinnaApiSearchTests
    {
        FinnaApiSearch search;
        HttpRequestMessage request;
        Uri uri;

        [TestInitialize()]
        public void SetUp()
        {
            search = new FinnaApiSearch()
            {
                BaseUrl = "https://api.finna.fi/api/v1/search",
                LookFor = "x",
                Building = "0/Heili/",
                PublishDate = "2018",
                Genre = "tieteiskirjallisuus",
                Fields = new List<string>() { "field1", "field2" }
            };
            request = search.CreateRequest();
            uri = request.RequestUri;
        }

        [TestMethod()]
        public void BasicValuesTest()
        {
            Assert.AreEqual(HttpMethod.Get, request.Method);
            Assert.AreEqual("https", uri.Scheme);
            Assert.AreEqual("api.finna.fi", uri.Host);
            Assert.AreEqual("/api/v1/search", uri.AbsolutePath);
        }

        [TestMethod()]
        public void QueryTest()
        {
            var query = request.RequestUri.Query;
            var message = "Query string should match the output generated by the API's Web UI";
            Assert.IsTrue(query.Contains("lookfor=x"), message);
            Assert.IsTrue(query.Contains("filter[]=building%3A0%2FHeili%2F"), message);
            Assert.IsTrue(query.Contains("filter[]=publishDate%3A2018"), message);
            Assert.IsTrue(query.Contains("filter[]=genre%3Atieteiskirjallisuus"), message);
            Assert.IsTrue(query.Contains("field[]=field1"), message);
            Assert.IsTrue(query.Contains("field[]=field2"), message);
        }
    }
}